"""
streamlit/app.py — AI & the Labor Market dashboard
Deploy as a Streamlit in Snowflake app.

All Snowflake queries run via the active session context;
no external credentials needed inside SiS.
"""

import streamlit as st
import pandas as pd
from snowflake.snowpark.context import get_active_session
from snowflake.cortex import Search

session = get_active_session()

st.set_page_config(page_title="AI & the Labor Market", layout="wide")

# ── Header ──────────────────────────────────────────────────────────────────
st.title("AI & the Labor Market")
st.caption(
    "Do the numbers back up the fear? Economic data + news sentiment analyzed with Snowflake Cortex AI."
)

tab1, tab2, tab3, tab4 = st.tabs(
    ["📈 Fear vs. Reality", "📰 Monthly Digest", "🔍 Semantic Search", "🏭 Sector Breakdown"]
)


# ── Tab 1: Fear vs. Reality ─────────────────────────────────────────────────
with tab1:
    st.subheader("AI Headlines vs. Actual Layoffs")
    st.markdown(
        "Monthly volume of news headlines citing AI as a causal factor in job losses, "
        "plotted against BLS total layoffs."
    )

    df = session.sql("""
        SELECT
          d.month,
          d.total_layoffs_k,
          d.unemployment_rate,
          d.ai_causal_count,
          d.headline_count
        FROM LABOR_MARKET.CORTEX.MONTHLY_DIGEST d
        ORDER BY d.month
    """).to_pandas()

    df["month"] = pd.to_datetime(df["MONTH"])

    col1, col2 = st.columns(2)
    with col1:
        st.line_chart(
            df.set_index("month")[["TOTAL_LAYOFFS_K"]],
            use_container_width=True,
        )
        st.caption("BLS Total Layoffs (thousands)")
    with col2:
        st.line_chart(
            df.set_index("month")[["AI_CAUSAL_COUNT"]],
            use_container_width=True,
        )
        st.caption("Headlines citing AI as job-loss cause (per month)")

    st.divider()
    st.subheader("Unemployment Rate Over Time")
    st.line_chart(df.set_index("month")[["UNEMPLOYMENT_RATE"]], use_container_width=True)

    # Correlation callout
    corr = df[["TOTAL_LAYOFFS_K", "AI_CAUSAL_COUNT"]].corr().iloc[0, 1]
    st.metric(
        "Pearson correlation: AI headline volume vs. actual layoffs",
        f"{corr:.2f}",
        help="A high correlation would suggest AI fears track real layoff trends. "
             "A low correlation suggests the fear cycle is decoupled from economic reality.",
    )


# ── Tab 2: Monthly Digest ───────────────────────────────────────────────────
with tab2:
    st.subheader("AI-Generated Monthly Economic Digest")
    st.markdown(
        "Each entry is a 3-sentence narrative generated by `AI_COMPLETE` (Mistral-7B), "
        "synthesizing BLS + FRED data with the month's news themes (via `AI_AGG`)."
    )

    months_df = session.sql("""
        SELECT month FROM LABOR_MARKET.CORTEX.MONTHLY_DIGEST ORDER BY month DESC
    """).to_pandas()

    selected = st.selectbox(
        "Select month",
        options=months_df["MONTH"].astype(str).tolist(),
    )

    digest_df = session.sql(f"""
        SELECT
          unemployment_rate,
          nonfarm_payroll_k,
          total_layoffs_k,
          headline_count,
          ai_causal_count,
          narrative_digest
        FROM LABOR_MARKET.CORTEX.MONTHLY_DIGEST
        WHERE month = '{selected}'
    """).to_pandas()

    if not digest_df.empty:
        row = digest_df.iloc[0]
        c1, c2, c3 = st.columns(3)
        c1.metric("Unemployment Rate", f"{row['UNEMPLOYMENT_RATE']:.1f}%")
        c2.metric("Total Layoffs (K)", f"{row['TOTAL_LAYOFFS_K']:,.0f}" if row['TOTAL_LAYOFFS_K'] else "N/A")
        c3.metric("AI-causal headlines", f"{int(row['AI_CAUSAL_COUNT'])} / {int(row['HEADLINE_COUNT'])}")

        st.markdown("### Narrative Digest")
        st.info(row["NARRATIVE_DIGEST"])

    st.divider()
    st.subheader("Monthly Themes (AI_AGG)")
    themes_df = session.sql(f"""
        SELECT theme_summary
        FROM LABOR_MARKET.CORTEX.MONTHLY_SENTIMENT_THEMES
        WHERE month = '{selected}'
    """).to_pandas()
    if not themes_df.empty:
        st.markdown(themes_df.iloc[0]["THEME_SUMMARY"])


# ── Tab 3: Semantic Search ──────────────────────────────────────────────────
with tab3:
    st.subheader("Semantic Headline Search")
    st.markdown(
        "Search the news corpus using natural language. "
        "Powered by Cortex Search + Arctic Embed embeddings."
    )

    query = st.text_input("Search headlines", placeholder="e.g. tech workers displaced by automation")

    category_filter = st.multiselect(
        "Filter by category",
        ["layoff", "hiring", "ai_fear", "ai_positive", "policy", "neutral"],
        default=[],
    )

    if query:
        # Use Cortex Search REST endpoint via session
        filter_expr = None
        if category_filter:
            filter_expr = {"@in": {"category": category_filter}}

        results = session.sql(f"""
            SELECT *
            FROM TABLE(
              LABOR_MARKET.CORTEX.HEADLINE_SEARCH!SEARCH(
                QUERY => '{query.replace("'", "''")}',
                COLUMNS => ['full_text', 'category', 'published_at', 'source_name', 'ai_causal_flag'],
                LIMIT => 20
              )
            )
        """).to_pandas()

        if results.empty:
            st.warning("No results found.")
        else:
            for _, r in results.iterrows():
                badge = "🔴 AI-causal" if r.get("AI_CAUSAL_FLAG") else ""
                st.markdown(
                    f"**{r['FULL_TEXT'][:120]}...** {badge}  \n"
                    f"_{r['SOURCE_NAME']} · {str(r['PUBLISHED_AT'])[:10]} · `{r['CATEGORY']}`_"
                )
                st.divider()


# ── Tab 4: Sector Breakdown ─────────────────────────────────────────────────
with tab4:
    st.subheader("Layoffs by Sector (BLS JOLTS)")

    sector_df = session.sql("""
        SELECT
          industry_name,
          DATE_FROM_PARTS(year, REPLACE(period, 'M', '')::INT, 1) AS month,
          value AS layoffs_k
        FROM LABOR_MARKET.RAW.RAW_BLS_JOLTS
        WHERE industry_name IS NOT NULL
          AND series_id LIKE '%LAY%'
        ORDER BY month, industry_name
    """).to_pandas()

    sector_df["month"] = pd.to_datetime(sector_df["MONTH"])

    pivot = sector_df.pivot_table(
        index="month", columns="INDUSTRY_NAME", values="LAYOFFS_K", aggfunc="sum"
    )

    st.line_chart(pivot, use_container_width=True)

    st.divider()
    st.subheader("Headline Category Distribution")
    cat_df = session.sql("""
        SELECT category, COUNT(*) AS n
        FROM LABOR_MARKET.CORTEX.NEWS_CLASSIFIED
        GROUP BY category
        ORDER BY n DESC
    """).to_pandas()
    st.bar_chart(cat_df.set_index("CATEGORY")["N"])
